apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'x509-certificate-exporter'
        static_configs:
          - targets: ['172.23.55.56:9793']

      - job_name: 'admission-webhook'
        static_configs:
          - targets:
            - pod-security-webhook-metrics.webhook-system.svc.cluster.local:9091
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 15s\n  evaluation_interval: 15s\n\nscrape_configs:\n  - job_name: 'prometheus'\n    static_configs:\n      - targets: ['localhost:9090']\n\n  - job_name: 'x509-certificate-exporter'\n    static_configs:\n      - targets: ['172.23.55.56:9793']\n\n  - job_name: 'admission-webhook'\n    static_configs:\n      - targets:\n          - admission-webhook.webhook-system.svc.cluster.local:8000\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-server-conf","namespace":"monitoring"}}
  creationTimestamp: "2025-10-20T13:57:03Z"
  name: prometheus-server-conf
  namespace: monitoring
  resourceVersion: "63813740"
  uid: 0889db33-4c17-41eb-bf12-61e19f8faa59