apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-security-webhook-pvc-reader-binding
subjects:
- kind: ServiceAccount
  name: pod-security-webhook
  namespace: webhook-system
roleRef:
  kind: ClusterRole
  name: pod-security-webhook-pvc-reader
  apiGroup: rbac.authorization.k8s.io