apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-security-webhook
  namespace: webhook-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-security-webhook
  template:
    metadata:
      labels:
        app: pod-security-webhook
    spec:
      containers:
      - name: webhook
        image: cemo07/pod-security-webhook:v1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: https
        - containerPort: 9091
          name: metrics
        volumeMounts:
        - name: tls-certs
          mountPath: /tls
          readOnly: true
        command: ["uvicorn"]
        args:
          - "app:app"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8443"
          - "--ssl-keyfile"
          - "/tls/tls.key"
          - "--ssl-certfile"
          - "/tls/tls.crt"
      volumes:
      - name: tls-certs
        secret:
          secretName: pod-security-webhook-tls