apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-security-webhook
webhooks:
- name: podsecurity.webhook.example.com
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Ignore
  clientConfig:
    service:
      name: pod-security-webhook
      namespace: webhook-system
      path: /validate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKVENDQWcyZ0F3SUJBZ0lVZnpWN0daUG02UUp0L2V3RmtkT0lnNU9janVvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lqRWdNQjRHQTFVRUF3d1hjRzlrTFhObFkzVnlhWFI1TFhkbFltaHZiMnN0WTJFd0hoY05NalV4TWpBMApNVEExTURJeldoY05Nall4TWpBME1UQTFNREl6V2pBaU1TQXdIZ1lEVlFRRERCZHdiMlF0YzJWamRYSnBkSGt0CmQyVmlhRzl2YXkxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1LNzdzNWQKRlh4MnpVYml4MndMMUlBVURWV3RsUDZWREhyY0hML29PbkhtK0o5alpvMkxRaFpiMDlIeEw0VlFBTUg4RVVrWQoyWU05eXN6a3U5aEFKRVlaT2RFcWVuN0NFUGVsdUhLY3I3akxra0Uzb2xWUmZnZkpWTS9PbDhhNVlBSG43TGFuCjBaWUdYZDdUYXpqUDhGSmV3bGdpUkxOR2ZTRDg0dVArRmhYMXFzeFBNM1BSQnhFMjZhRWxuU3F5WjltMlEzN1MKdE5yZURRdFNNU3JrMHN1WlkwTGt1QVYwdVF2M1pXTVJZSzFLbVQwdUFxOHdncUgwVjhUZUdUaVlxNnFDOTRLdgo3WXBlSnpML00rRGptMkJlbEo1UTcveTBDcnltcTE2akRZR0pyTG5vU0ljTDN6UkxXb3FYWUd1ME93dTVYZGJ6Ck51MDVEVzNqVURpb3JOMENBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGRFVhN0ptNndxZVY3cy96YnZMWGl6VTUKY2o2R01COEdBMVVkSXdRWU1CYUFGRFVhN0ptNndxZVY3cy96YnZMWGl6VTVjajZHTUE4R0ExVWRFd0VCL3dRRgpNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIZm1tcjltMlUwcFNCNC9pMXVPYnp3TC9tN0RTVmVNCmhIcmpHWUpsWXJIU0t4NS9WYUlWa2MxamFOSERSalZOeUZqOE4xditSMTNtZU9RR3oyQ0tTTzMwNWcxNzgxd1AKVWRoK0dqbDhtZjZKcFV5enFCM1h1T01KNlpWWWtSZ1MzR3BWZkczdVNoZzdUVWp0UldUSE52dHl5S3pGQVF5TwpocUNmS1NLTkc2VE93dTNJTW9GUVBMK3lUcllFZmpTQS9GY1FMRWZVdE1DN24vSTE3WjdVcUlLamNIWlZKaUdzCmVkdU5EMDZTNGx4cTZ6OVkySit4dXpuTk5YaTA5YVhscUJHQ3N1SHdHbDR2NFQ5VDZZaWlmWEtKMS9aU2hDNzcKOS9uSjM5c1dSR1dvZWVvWG95SjQ3QW04azdLNFNBZjVPMFBFR1hlRHpzTHFqb1dsekg4WEdxVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]