apiVersion: v1
kind: Pod
metadata:
  name: deny-hostpath
  namespace: webhook-system
  labels:
    webhook: enabled
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    volumeMounts:
    - name: hp
      mountPath: /data
  volumes:
  - name: hp
    hostPath:
      path: /tmp